language: java

jdk: 
  - oraclejdk8

sudo: false

dist: trusty

cache:
  directories:
    - $HOME/.m2/
    - $HOME/.sonar/

script: 
  - ./mvnw clean install
  - bash <(curl -s https://codecov.io/bash)
