server:
  port: 4236
  
logging:
  level:
    com.saalamsaifi.auto.roster: debug
    org:
      mongodb: info
      springframework.boot.autoconfigure.mongo.embedded: info

spring:
  data:
    mongodb:
      host: "localhost"
      database: "auto_roster_test"
      