management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
server:
  port: 4236
  
logging:
  level:
    com.saalamsaifi.auto.roster: trace

spring:
  data:
    mongodb:
      host: "localhost"
      database: "auto_roster"