server:
  port: 4236
  
logging:
  level:
    com.saalamsaifi.auto.roster: trace

#spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,  org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration 